name: sample github action workflow
on: [push]
jobs:
  example-job:
      runs-on: ubuntu-latest
      steps:
          - name: Echo a String
            run: echo "this is simple message"

  next-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo multi line string
        run: |
          echo "This is first line"
          echo "This is second line"
          echo "This is third line"